stages:
- test
- docker-publish
- deploy

eslint:
  image: node:latest
  stage: test
  retry: 2
  script:
    - npm install @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint
    - npm run test:lint

sast:
  stage: test
  retry: 2
  only:
    - main
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

docker-publish:
  image: docker:latest
  stage: docker-publish
  retry: 2
  only:
    - main
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_PATH${tag}" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_PATH${tag}"

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  retry: 2
  only:
    - main
  script:
    - kubectl config get-contexts
    - kubectl config use-context streaks/streaks:streaks
    - kubectl config set-context --current --namespace=streaks
    - kubectl rollout restart deployment streaks
  environment:
    name: production
    url: https://streaks.chevro.fr
