version: "3.9"
services:
  db:
    image : mongo:5.0.8
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
    - ./database:/data/db

  streaks:
    build: .
    container_name: "streaks"
    restart: always
    depends_on:
      - db
    environment:
      - TZ=${TZ}
      - MONGO_URI=mongodb://db:27017/?retryWrites=true&w=majority
    ports:
      - ${PORT}:80
    volumes:
      - ./.env:/streaks/.env
