version: "3.9"
services:
  db:
    image : mongo:5.0.8
    container_name: mongodb
    restart: always
    volumes:
    - ./database:/data/db

  streaks:
    # If you want to build from Dockerfile
    build: .
    # If you want to use image
    # image: "registry.chevro.fr/streaks/streaks:latest"
    container_name: "streaks"
    restart: always
    depends_on:
      - db
    environment:
      - TZ=${TZ}
      - MONGO_URI=mongodb://db:27017/?retryWrites=true&w=majority
    ports:
      - ${PORT}:80
    volumes:
      - ./.env:/streaks/.env
